
import { Product, Category, Language } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'apps',
    name: 'التطبيقات',
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1000&auto=format&fit=crop', // Netflix/Services vibe
    dataKey: 'Services',
    bgColor: 'from-purple-600 to-indigo-900'
  },
  {
    id: 'games',
    name: 'الألعاب',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1000&auto=format&fit=crop', // Gaming vibe
    dataKey: 'Games',
    bgColor: 'from-orange-600 to-red-900'
  },
  {
    id: 'cards',
    name: 'البطاقات',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f7a07d?q=80&w=1000&auto=format&fit=crop', // Payment/Cards vibe
    dataKey: 'Cards',
    bgColor: 'from-blue-600 to-cyan-900'
  }
];

export const PRODUCTS: Product[] = []; // Default empty, populated from Firestore usually

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ar: {
    home: 'الرئيسية',
    store: 'المتجر',
    profile: 'حسابي',
    orders: 'سجل الطلبات',
    admin: 'لوحة التحكم',
    search_placeholder: 'ابحث عن لعبة أو بطاقة...',
    login: 'دخول',
    logout: 'تسجيل الخروج',
    balance: 'رصيدك',
    menu: 'القائمة',
    customer_service: 'خدمة العملاء',
    created_by: 'برمجة وتصميم بواسطة FILEX',
    all_rights_reserved: 'جميع الحقوق محفوظة © 2025',
    latest_offers: 'أحدث العروض والأخبار',
    browse_store: 'تصفح المتجر',
    no_products: 'لا توجد منتجات متاحة حالياً.',
    buy_now: 'شراء فوري',
    whatsapp_order: 'واتساب',
    amount_usd: 'المبلغ بالدولار ($)',
    player_id: 'معرف اللاعب (ID)',
    you_get: 'ستحصل على:',
    wallet: 'المحفظة',
    settings: 'الإعدادات',
    edit_profile: 'تعديل الملف الشخصي',
    save_changes: 'حفظ التغييرات',
    order_status_pending: 'قيد المراجعة',
    order_status_completed: 'مكتمل',
    order_status_rejected: 'مرفوض',
    no_orders: 'لا توجد طلبات سابقة',
    quantity: 'الكمية',
    price: 'السعر',
    date: 'التاريخ',
    welcome: 'مرحباً',
    notifications: 'الإشعارات',
    official_messages: 'الرسائل الرسمية',
    system_messages: 'رسائل النظام',
    no_notifications: 'لا توجد إشعارات حالياً',
    mark_all_read: 'تحديد الكل كمقروء',
    privacy_policy: 'سياسة الخصوصية',
    about_us: 'من نحن',
    about_desc: 'تعرف على قصة متجر FILEX Store وأهدافنا.',
    privacy_desc: 'كيف نحمي بياناتك وحقوقك في المتجر.'
  },
  en: {
    home: 'Home',
    store: 'Store',
    profile: 'Profile',
    orders: 'Order History',
    admin: 'Admin Panel',
    search_placeholder: 'Search for game or card...',
    login: 'Login',
    logout: 'Logout',
    balance: 'Balance',
    menu: 'Menu',
    customer_service: 'Customer Service',
    created_by: 'Created by FILEX',
    all_rights_reserved: 'All Rights Reserved © 2025',
    latest_offers: 'Latest Offers & News',
    browse_store: 'Browse Store',
    no_products: 'No products available currently.',
    buy_now: 'Buy Now',
    whatsapp_order: 'WhatsApp',
    amount_usd: 'Amount ($)',
    player_id: 'Player ID',
    you_get: 'You will get:',
    wallet: 'Wallet',
    settings: 'Settings',
    edit_profile: 'Edit Profile',
    save_changes: 'Save Changes',
    order_status_pending: 'Pending',
    order_status_completed: 'Completed',
    order_status_rejected: 'Rejected',
    no_orders: 'No previous orders',
    quantity: 'Qty',
    price: 'Price',
    date: 'Date',
    welcome: 'Welcome',
    notifications: 'Notifications',
    official_messages: 'Official Messages',
    system_messages: 'System Messages',
    no_notifications: 'No notifications',
    mark_all_read: 'Mark all as read',
    privacy_policy: 'Privacy Policy',
    about_us: 'About Us',
    about_desc: 'Learn about FILEX Store and our goals.',
    privacy_desc: 'How we protect your data and rights.'
  },
  fr: {
    home: 'Accueil',
    store: 'Magasin',
    profile: 'Profil',
    orders: 'Historique',
    admin: 'Panneau Admin',
    search_placeholder: 'Rechercher un jeu...',
    login: 'Connexion',
    logout: 'Déconnexion',
    balance: 'Solde',
    menu: 'Menu',
    customer_service: 'Service Client',
    created_by: 'Créé par FILEX',
    all_rights_reserved: 'Tous droits réservés © 2025',
    latest_offers: 'Dernières offres',
    browse_store: 'Parcourir le magasin',
    no_products: 'Aucun produit disponible.',
    buy_now: 'Acheter',
    whatsapp_order: 'WhatsApp',
    amount_usd: 'Montant ($)',
    player_id: 'ID Joueur',
    you_get: 'Vous obtiendrez:',
    wallet: 'Portefeuille',
    settings: 'Paramètres',
    edit_profile: 'Modifier le profil',
    save_changes: 'Enregistrer',
    order_status_pending: 'En attente',
    order_status_completed: 'Terminé',
    order_status_rejected: 'Rejeté',
    no_orders: 'Aucune commande',
    quantity: 'Qté',
    price: 'Prix',
    date: 'Date',
    welcome: 'Bienvenue',
    notifications: 'Notifications',
    official_messages: 'Messages officiels',
    system_messages: 'Messages système',
    no_notifications: 'Pas de notifications',
    mark_all_read: 'Tout marquer comme lu',
    privacy_policy: 'Politique de confidentialité',
    about_us: 'À propos de nous',
    about_desc: 'Découvrez l\'histoire de FILEX Store.',
    privacy_desc: 'Comment nous protégeons vos données.'
  }
};
